### ISSUE TITLE
java.lang.NoSuchMethodError after upgrading the firebase performance sdk version

### ISSUE THREAD

**Issue by deepanshu42** [firebase/firebase-android-sdk#3829]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Arctic fox | 2022.3.1
  * Firebase Component: Performace
  * Component version: 20.1.0

### [REQUIRED] Step 3: Android app getting crashed after upgrading performance sdk version from 20.0.4 to 20.1.0

```
FATAL EXCEPTION: firebase-iid-executor
java.lang.NoSuchMethodError: No virtual method toInstant()Lorg/threeten/bp/Instant; in class Ljava/util/Date; or its super classes (declaration of 'java.util.Date' appears in /system/framework/core-oj.jar)
        at com.google.firebase.heartbeatinfo.HeartBeatInfoStorage.getFormattedDate(SourceFile:139)
        at com.google.firebase.heartbeatinfo.HeartBeatInfoStorage.isSameDateUtc(SourceFile:206)
        at com.google.firebase.heartbeatinfo.HeartBeatInfoStorage.shouldSendSdkHeartBeat(SourceFile:216)
        at com.google.firebase.heartbeatinfo.HeartBeatInfoStorage.shouldSendGlobalHeartBeat(SourceFile:232)
        at com.google.firebase.heartbeatinfo.DefaultHeartBeatController.getHeartBeatCode(SourceFile:167)
        at com.google.firebase.iid.GmsRpc.setDefaultAttributesToBundle(SourceFile:19)
        at com.google.firebase.iid.GmsRpc.startRpc(SourceFile:1)
        at com.google.firebase.iid.GmsRpc.getToken(SourceFile:1)
        at com.google.firebase.iid.FirebaseInstanceId.lambda$getInstanceId$2$FirebaseInstanceId(SourceFile:1)
        at com.google.firebase.iid.FirebaseInstanceId$$Lambda$3.start(Unknown Source:10)
        at com.google.firebase.iid.RequestDeduplicator.getOrStartGetTokenRequest(SourceFile:7)
        at com.google.firebase.iid.FirebaseInstanceId.lambda$getInstanceId$3$FirebaseInstanceId(SourceFile:5)
        at com.google.firebase.iid.FirebaseInstanceId$$Lambda$0.then(Unknown Source:6)
        at com.google.android.gms.tasks.zze.run(SourceFile:1)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at com.google.android.gms.common.util.concurrent.zza.run(SourceFile:2)
        at java.lang.Thread.run(Thread.java:764)
```

#### Steps to reproduce:
Just updated the `firebase-perf` version and the application started crashing on every app open

**Comment by deepanshu42** [comment]
This is resolved by adding the following rule in proguard:
```
-keep public class java.util.Date {
  public *;
}
```

**Comment by deepanshu42** [comment]
This is still happening. Can someone please check?

**Comment by argzdev** [comment]
I'm tried replicating this issue on a clean project with version `implementation 'com.google.firebase:firebase-perf-ktx:20.1.0'`, however unable to reproduce the issue. Could you show my code snippets from your gradle file? Are you able to create an [MCVE](https://stackoverflow.com/help/minimal-reproducible-example)? That'll greatly help us in our investigation. Thanks

**Comment by jeremyjiang-dev** [comment]
@deepanshu42  @DaireJN From the log, I saw `com.google.firebase.iid.FirebaseInstanceId`, which was deprecated in October, 2020. ([Release notes](https://firebase.google.com/support/release-notes/android#iid_v21-0-0)) You might have old dependencies on this deprecated package. 

Could you update Firebase libraries to their latest versions? Please feel free to share your `build.gradle` file and we can assist you on diagnosing any deprecated dependencies.

**Comment by DaireJN** [comment]
@jeremyjiang-dev I haven't been able to replicate this issue on a clean project for now com.google.firebase:firebase-bom:29.1.0 is working fine

**Comment by jeremyjiang-dev** [comment]
@DaireJN Gotcha! Thanks for reporting this. Please let us know if you encounter any problems.
