### ISSUE TITLE
Firebase java.lang.ClassNotFoundException with gradle:4.0.0 

### ISSUE THREAD

**Issue by TNorth22** [firebase/firebase-android-sdk#1441]
* Android Studio version: 4.0 Beta 4
  * Firebase Component: Remote Config
  * Component version: 19.1.3

#### Steps to reproduce:

After upgrading AS to 4.0 Beta and project to gradle build tools to `com.android.tools.build:gradle:4.0.0-beta04` project compiles but it appears R classes are missing and project crashes at runtime.  This looks super familiar to another issue reported to google for gradle 3.6.0-rc-01 if that's helpful: https://issuetracker.google.com/issues/147968317

I'm using the following firebase libs:
```

    implementation 'com.google.firebase:firebase-config:19.1.3'
    implementation 'com.google.firebase:firebase-analytics:17.3.0'
    implementation 'com.google.firebase:firebase-appindexing:19.1.0'
```

#### Relevant Code:

```
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/R$string;
        at com.google.android.gms.common.internal.StringResourceValueReader.<init>(com.google.android.gms:play-services-basement@@17.2.1:4)
        at com.google.firebase.FirebaseOptions.fromResource(com.google.firebase:firebase-common@@19.3.0:156)
        at com.google.firebase.FirebaseApp.initializeApp(com.google.firebase:firebase-common@@19.3.0:244)
        at com.google.firebase.provider.FirebaseInitProvider.onCreate(com.google.firebase:firebase-common@@19.3.0:51)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1940)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1915)
        at com.google.firebase.provider.FirebaseInitProvider.attachInfo(com.google.firebase:firebase-common@@19.3.0:45)
        at android.app.ActivityThread.installProvider(ActivityThread.java:6682)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6229)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6144)
        at android.app.ActivityThread.access$1200(ActivityThread.java:235)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1768)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:6990)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.R$string" on path: DexPathList[[zip file "/data/app/com.picmonkey.picmonkey-1kgpGFItO1NvMFyERe8fOw==/base.apk"],nativeLibraryDirectories=[/data/app/com.<omitted>.<omitted>-1kgpGFItO1NvMFyERe8fOw==/lib/arm64, /data/app/com.<omitted>.<omitted>-1kgpGFItO1NvMFyERe8fOw==/base.apk!/lib/arm64-v8a, /system/lib64]]
```

**Comment by TNorth22** [comment]
Any movement on this?

**Comment by AssylkhanovAslan** [comment]
Try changing the gradle version to an older version. I have had similar issue. Resolved it by changing gradle version from 3.6.3 to 3.5.3

**Comment by vkryachko** [comment]
Feel free to reopen if the issue persists in the latest version of AS.
