### ISSUE TITLE
Hit error when upgrade firebase-admin 6.9.0 to 9.1.1

### ISSUE THREAD

**Issue by tasyachiru** [firebase/firebase-android-sdk#4901]
Dear All,

I would like to ask you, after we upgrade firebase admin to the latest version, its hit this error

Exception in thread "main" java.lang.NoSuchMethodError: com.google.firebase.messaging.Notification.(Ljava/lang/String;Ljava/lang/String;)V
        at com.ebworx.helper.notification.service.FCMService.sendMessageToMultipleDeviceSync(FCMService.java:155)
        at com.ebworx.batch.result.PushNotificationSendProcessResultJob.pushNotificationToDevice(PushNotificationSendProcessResultJob.java:92)
        at com.ebworx.batch.result.PushNotificationSendProcessResultJob.manageResultJob(PushNotificationSendProcessResultJob.java:62)
        at com.ebworx.batch.result.AbstractProcessResultJob.processResultJob(AbstractProcessResultJob.java:36)
        at com.ebworx.batch.controller.AbstractWorkerController.processWork(AbstractWorkerController.java:389)
        at com.ebworx.batch.controller.PushNotificationSendController.main(PushNotificationSendController.java:101)

may i know what method that different from version 6.9.0 to 9.1.1?

**Comment by tasyachiru** [comment]
The error pointing to push notification code

public void sendMessageToMultipleDevicesync PushNotificationRequest request) throws ExecutionException{
List registrationTokens = request. getTokenList ();
Map<String
‚String> customMap = request-getCustomPropertyMap() ;
String notificationId = customMap.get("notificationId");
logger. info"FC push start. Notification Id:"+notificationId);
MulticastMessage message = MulticastMessage. buitder()
setNotification (new Notification(request. getTitle(), request. getMessage() ))
putAllData(request. getCustomPropertyMap () )
.addAllTokens(registrationTokens)
.build() ;
try {
BatchResponse batchResponse = FirebaseMessaging. getInstance). sendMulticastAsync(message). get ();
if (batchResponse. getFailureCount() > 0)
List ‹SendResponse› responses = batchResponse. getResponses() ;
List failedTokens = new ArrayList<>();
for (int i = 0; i < responses.size(); iH) {
if (responses.get (i).isSuccessful ()) {
// The order of responses corresponds to the order of the registration tokens.
failedTokens.add(registrationTokens.get (i));
logger. info "List of tokens that caused failures: " + failedTokens);
logger. info"FC push done. [total of device token = " + registrationTokens.size() + "][success = " + (batchResponse. getSuccessCount ()) + "]");
}catch(InterruptedException e)
logger. error("Sending a push notification ["+notificationId+"] was interrupted", e);

**Comment by argzdev** [comment]
Hi @tasyachiru, thanks for reporting. Could you file an issue to our [firebase-admin-java](https://github.com/firebase/firebase-admin-java/issues) repository? It is better suited for our specialists in that repo to handle your issue. That said, I'll close this issue now. Feel free to ask this to be reopened if you think this is a mistake or if you have further information that the issue is on the Firebase Android SDK side. Thanks!
