### ISSUE TITLE
Firebase InApp Messaging not working with Android OS 6.0.1

### ISSUE THREAD

**Issue by meetsagarlandge25** [firebase/firebase-android-sdk#630]
Android Studio : v3.4.1
InApp Firebase : 'com.google.firebase:firebase-inappmessaging-display:18.0.2'

**I am trying to integrate Firebase InApp messaging in my android application. After adding below dependency in gradle  'com.google.firebase:firebase-inappmessaging-display:18.0.2'**

Its throwing below error :
 FATAL EXCEPTION: RxCachedThreadScheduler-1 io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling |
 
java.lang.NoClassDefFoundError: com.google.common.base.CharMatcher at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367) at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:69) at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57) at java.util.concurrent.FutureTask.run(FutureTask.java:237) at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154) at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) at java.lang.Thread.run(Thread.java:818)

**Caused by: java.lang.NoClassDefFoundError: com.google.common.base.CharMatcher at com.google.common.base.Splitter.on(Splitter.java:125) at io.grpc.internal.GrpcUtil.(GrpcUtil.java:203) at io.grpc.internal.AbstractManagedChannelImplBuilder.(AbstractManagedChannelImplBuilder.java:84) at io.grpc.okhttp.OkHttpChannelBuilder.forTarget(OkHttpChannelBuilder.java:119) at io.grpc.okhttp.OkHttpChannelProvider.builderForTarget(OkHttpChannelProvider.java:48) at io.grpc.okhttp.OkHttpChannelProvider.builderForTarget(OkHttpChannelProvider.java:27) at io.grpc.ManagedChannelBuilder.forTarget(ManagedChannelBuilder.java:73) at com.google.firebase.inappmessaging.internal.injection.modules.GrpcChannelModule.providesGrpcChannel(com.google.firebase:firebase-inappmessaging@@18.0.2:41) at com.google.firebase.inappmessaging.internal.injection.modules.GrpcChannelModule_ProvidesGrpcChannelFactory.providesGrpcChannel(com.google.firebase:firebase-inappmessaging@@18.0.2:36) at com.google.firebase.inappmessaging.internal.injection.modules.GrpcChannelModule_ProvidesGrpcChannelFactory.get(com.google.firebase:firebase-inappmessaging@@18.0.2:26) at com.google.firebase.inappmessaging.internal.injection.modules.GrpcChannelModule_ProvidesGrpcChannelFactory.get(com.google.firebase:firebase-inappmessaging@@18.0.2:9) at dagger.internal.DoubleCheck.get(DoubleCheck.java:47) at com.google.firebase.inappmessaging.internal.injection.components.DaggerUniversalComponent.gRPCChannel(com.google.firebase:firebase-inappmessaging@@18.0.2:280) at com.google.firebase.inappmessaging.internal.injection.components.DaggerAppComponent$com_google_firebase_inappmessaging_internal_injection_components_UniversalComponent_gRPCChannel.get(com.google.firebase:firebase-inappmessaging@@18.0.2:437) at com.google.firebase.inappmessaging.internal.injection.components.DaggerAppComponent$com_google_firebase_inappmessaging_internal_injection_components_UniversalComponent_gRPCChannel.get(com.google.firebase:firebase-inappmessaging@@18.0.2:424) at com.google.firebase.inappmessaging.internal.injection.modules.GrpcClientModule_ProvidesInAppMessagingSdkServingStubFactory.get(com.google.firebase:firebase-inappmessaging@@18.0.2:35) at com.google.firebase.inappmessaging.internal.injection.modules.GrpcClientModule_ProvidesInAppMessagingSdkServingStubFactory.get(com.google.firebase:firebase-inappmessaging@@18.0.2:11) at dagger.internal.DoubleCheck.get(DoubleCheck.java:47) at com.google.firebase.inappmessaging.internal.GrpcClient_Factory.get(com.google.firebase:firebase-inappmessaging@@18.0.2:23) at com.google.firebase.inappmessaging.internal.GrpcClient_Factory.get(com.google.firebase:firebase-inappmessaging@@18.0.2:8) at dagger.internal.DoubleCheck.get(DoubleCheck.java:47) at com.google.firebase.inappmessaging.internal.ApiClient.getFiams(com.google.firebase:firebase-inappmessaging@@18.0.2:8)**

**This works fine with other Android OS , have verified with 7.0, 8.0 and 9.0. 
**Note** : Have added androidx support**

**these are my gradle dependencies:**

    implementation 'com.google.android.gms:play-services-analytics:17.0.0'
    implementation 'androidx.appcompat:appcompat:1.0.2'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'androidx.media:media:1.0.1'
    implementation 'androidx.vectordrawable:vectordrawable-animated:1.0.0'
    implementation 'com.google.android.material:material:1.0.0'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    implementation 'com.google.guava:guava:28.0-jre'
    //noinspection GradleDependency
    implementation 'com.google.dagger:dagger:2.21'
    //noinspection GradleDependency
    kapt 'com.google.dagger:dagger-compiler:2.21'
    //noinspection GradleDependency,OutdatedLibrary
    implementation 'com.google.dagger:dagger-android:2.21'
    //noinspection GradleDependency
    implementation 'com.google.dagger:dagger-android-support:2.21'
    //noinspection GradleDependency
    kapt 'com.google.dagger:dagger-android-processor:2.21'
    compileOnly 'javax.annotation:jsr250-api:1.0'
    implementation 'com.squareup.retrofit2:retrofit:2.4.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.4.0'
    implementation 'com.squareup.retrofit2:adapter-rxjava:2.3.0'
    implementation 'com.squareup.retrofit2:adapter-rxjava2:2.3.0'
    implementation 'com.squareup.okhttp3:okhttp:3.10.0'
    implementation 'com.squareup.okhttp3:logging-interceptor:3.9.1'
    implementation 'io.reactivex.rxjava2:rxjava:2.2.6'
    implementation 'io.reactivex.rxjava2:rxandroid:2.1.1'
    implementation 'io.reactivex:rxandroid:1.2.1'
    implementation 'io.reactivex:rxjava:1.3.0'
    implementation 'androidx.recyclerview:recyclerview:1.0.0'
**Can you please help me out in this ?**

**Comment by moemawari** [comment]
I have the same issue. I get crashes on android 6 when I integrated Fire-base In app messaging. I get a No class def found error for grpc. Any suggestions? 
java.lang.NoClassDefFoundError
io.grpc.internal.GrpcUtil.<clinit>

**Comment by achuinard** [comment]
I forget what the resolution was. It might have been either upgrade your project to Java 8 (or, actually, downgrade it to Java 7), or the resolution may have been to just upgrade to the latest inappmessaging-display lib.

**Comment by moemawari** [comment]
I am using the latest in app messaging. As far as java is use this... C:\Program Files\Android\Android Studio\jre. Not sure what version. Do you know what version i need to use and how i can set it?

**Comment by aguatno** [comment]
Hi folks, sorry for the very late response here. I'm currently not seeing this error on the latest version of inappmessaging-display (19.0.3). In case you're still having issues, please let me know so I can continue on with the investigation.
